"""
LLM client for the chatbot -- uses OpenAI's Responses API
(client.responses.create), which is the current recommended interface
for the GPT-5.6 family (Sol/Terra/Luna) and what the deployed API key
was verified against directly.

Deliberately provider-agnostic at the call site: nothing else in the
codebase imports OpenAI directly or hardcodes a model name. Every
tunable comes from an environment variable, so switching
model/provider/timeout/temperature later is a config change, not a
code change:

    OPENAI_API_KEY           -- if unset, the chatbot runs in mock mode
    OPENAI_CHAT_MODEL         -- defaults to "gpt-5.6-luna"
    OPENAI_BASE_URL            -- optional, points at any
                                  OpenAI-compatible endpoint (Gemini's
                                  OpenAI-compatible endpoint, Azure
                                  OpenAI, a proxy, etc.)
    OPENAI_MAX_REPLY_TOKENS     -- optional, caps output length
                                   (default 500)
    OPENAI_TEMPERATURE           -- optional, default 0.3 (low --
                                    steadier, less erratic replies for
                                    a safety-adjacent product)
    OPENAI_TIMEOUT_SECONDS        -- optional, default 300

Mock mode (no API key set) is not an error state -- it lets the rest
of the chat system (persistence, safety monitoring, UI) be built and
tested end-to-end before any billing is involved, and it's what keeps
the demo running if the key is ever missing/invalid/rate-limited/out
of quota. Every external-call failure path falls back to a mock reply
rather than raising, so a bad API key or an OpenAI outage never takes
the rest of the app down with it.
"""

import os
from typing import List, Optional

from src.logging.logger import logger

DEFAULT_MODEL = "gpt-5.6-luna"
DEFAULT_MAX_TOKENS = 500  # bounds worst-case cost per reply
DEFAULT_TEMPERATURE = 0.3  # low -- steadier, more consistent tone
DEFAULT_TIMEOUT_SECONDS = 300

# How many of the most recent messages are actually sent to the model.
# Without this, a long-running chat would resend its *entire* history
# on every single turn -- cost and latency would grow without bound as
# the conversation gets longer. The full history is still kept for the
# safety pipeline (see conversation_analyzer) and for display in the
# UI; this limit only affects what the LLM itself sees.
MAX_HISTORY_MESSAGES = 20  # ~10 back-and-forth turns

CONNECTION_ERROR_MESSAGE = "ارتباط برقرار نشد. لطفاً دوباره تلاش کنید."


class ChatbotError(Exception):
    """Raised when a chat reply couldn't be generated by any available path."""


def is_live() -> bool:
    """True if a real API key is configured (vs. mock mode)."""
    return bool(os.environ.get("OPENAI_API_KEY"))


def _build_system_prompt(risk_level: Optional[str]) -> str:
    """
    Base instructions per the product's safety requirements: supportive,
    never diagnostic, and explicitly aware that it operates alongside a
    separate safety analyzer whose result it should defer to -- it does
    not run its own risk judgment, it reflects the analyzer's.
    """

    base = (
        "You are a warm, supportive conversational companion. "
        "Your role is to listen, understand, and help the person reflect on "
        "what they are experiencing. "
        "You are not a therapist, doctor, or mental health professional. "
        "Do not diagnose mental health conditions, label a person's mental state, "
        "or claim certainty about what someone is experiencing. "
        "Respond like a caring human in a real conversation. "
        "Start by acknowledging the person's feelings and experience before "
        "giving suggestions. Ask gentle, relevant follow-up questions when "
        "needed to understand their situation better. "
        "Keep responses natural, concise, and personal to what the person shared. "
        "Avoid lectures, generic motivational quotes, overly clinical language, "
        "or responses that feel like a scripted chatbot. "
        "A separate safety analyzer provides risk information. Always treat "
        "the safety analysis result provided by the analyzer as the source of "
        "truth for safety-related responses. Do not independently classify "
        "risk or announce that you detected a risk level. "
        "For low-risk conversations, focus on listening, emotional support, "
        "and normal conversation. Do not introduce crisis questions or emergency "
        "language unless the person's message contains clear safety concerns. "
        "For moderate concern, provide additional warmth and encouragement, "
        "help the person feel supported, and gently explore their situation "
        "without making the interaction feel like an intervention. "
        "For high-risk situations indicated by the safety analyzer, prioritize "
        "compassion and immediate emotional support, and encourage human support "
        "-- connecting with trusted people or appropriate emergency resources -- "
        "when necessary. Remain calm, warm, and non-judgmental. "
        "Do not suggest professional help immediately in ordinary low-risk "
        "conversations unless difficulties are persistent, severe, worsening, "
        "or significantly affecting daily functioning."
    )
    risk_level = (risk_level or "").lower()

    if risk_level in ("high", "critical", "high risk", "critical emergency"):
        base += (
            " Current analyzer result: HIGH RISK. "
            "Respond with extra warmth and care. "
            "Encourage the person to connect with trusted support or crisis "
            "resources when appropriate, without sounding clinical or alarming."
        )
    elif risk_level in ("moderate", "moderate risk", "mild concern"):
        base += (
            " Current analyzer result: MODERATE CONCERN. "
            "Be more attentive and supportive than usual while keeping the "
            "conversation natural and not overwhelming."
        )

    return base


def generate_reply(
    history: List[dict],
    risk_level: Optional[str] = None,
) -> dict:
    """
    history: list of {"role": "user"|"assistant", "content": str}, oldest
    first. Only the most recent MAX_HISTORY_MESSAGES are actually sent
    to the model -- see the module docstring.

    Returns {"reply": str, "mode": "live"|"error", "usage": {...}}.
    `usage` is {"prompt_tokens", "completion_tokens", "total_tokens"}
    (normalized from the Responses API's input_tokens/output_tokens
    naming, so the rest of the app -- persistence, the /chat endpoint --
    doesn't need to know which OpenAI API generated it), all zero when
    mode is "error".

    On any failure (no key configured, invalid key, network/timeout,
    provider outage, empty response), this returns the honest
    CONNECTION_ERROR_MESSAGE as the reply rather than a canned/mock
    line -- a broken connection should look broken, not like a normal
    (if generic) bot reply, especially once this is a live production
    system rather than a local dev placeholder.
    """

    empty_usage = {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0}

    api_key = os.environ.get("OPENAI_API_KEY")

    if not api_key:
        logger.error("Chatbot: OPENAI_API_KEY is not set.")
        return {
            "reply": CONNECTION_ERROR_MESSAGE,
            "mode": "error",
            "usage": empty_usage,
        }

    model = os.environ.get("OPENAI_CHAT_MODEL", DEFAULT_MODEL)
    base_url = os.environ.get("OPENAI_BASE_URL") or None
    max_tokens = int(os.environ.get("OPENAI_MAX_REPLY_TOKENS", DEFAULT_MAX_TOKENS))
    temperature = float(os.environ.get("OPENAI_TEMPERATURE", DEFAULT_TEMPERATURE))
    timeout = int(os.environ.get("OPENAI_TIMEOUT_SECONDS", DEFAULT_TIMEOUT_SECONDS))

    windowed_history = history[-MAX_HISTORY_MESSAGES:]

    try:
        from openai import OpenAI

        client = OpenAI(api_key=api_key, base_url=base_url, timeout=timeout)

        stream = client.responses.create(
            model=model,
            instructions=_build_system_prompt(risk_level),
            input=windowed_history,
            max_output_tokens=max_tokens,
            stream=True,
        )

        # Streamed internally and joined into one final string -- the
        # /chat/*/message endpoint's response shape (and the frontend)
        # stay exactly the same as before. stream=True is still used on
        # the actual API call (as verified against the live key), it's
        # just consumed to completion server-side rather than relayed
        # token-by-token to the browser. True live token streaming to
        # the UI would need a separate SSE/chunked-response endpoint --
        # happy to build that as a follow-up if wanted.
        text_parts = []
        usage_obj = None

        for event in stream:
            event_type = getattr(event, "type", None)

            if event_type == "response.output_text.delta":
                text_parts.append(event.delta)
            elif event_type == "response.completed":
                usage_obj = getattr(event.response, "usage", None)

        reply = "".join(text_parts).strip()

        if not reply:
            raise ChatbotError("Empty response from the model.")

        usage_dict = (
            {
                "prompt_tokens": getattr(usage_obj, "input_tokens", 0),
                "completion_tokens": getattr(usage_obj, "output_tokens", 0),
                "total_tokens": getattr(usage_obj, "total_tokens", 0),
            }
            if usage_obj
            else empty_usage
        )

        return {"reply": reply, "mode": "live", "usage": usage_dict}

    except Exception as exc:
        # Deliberately broad: an invalid key, expired quota, network
        # blip, or a provider outage all land here. Logged at ERROR
        # (not WARNING) since this is always an actionable problem now
        # that a real key is configured -- there's no expected/normal
        # no-key case left to distinguish it from.
        logger.error("Chatbot: LLM call failed (%s)." % exc)
        return {
            "reply": CONNECTION_ERROR_MESSAGE,
            "mode": "error",
            "usage": empty_usage,
        }
